/// Flutter icons NavIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavIcons
///      fonts:
///       - asset: fonts/NavIcons.ttf
///
///
///
import 'package:flutter/cupertino.dart';

class NavIcons {
  NavIcons._();

  static const _kFontFam = 'navicon';
  static const String? _kFontPkg = null;

  static const IconData ic_profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_wishlist = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_cart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}